Updated Quill Styles, Questions, and Text
vthacks-org/quill pull request #1
Opened 2017-12-24 17:34 UTC by mecolmg

2017-12-25 03:58 UTC, sarj21 commented on app/client/views/admin/user/user.html
>             ng-hide="isMitStudent">
change isMitStudent -> isVTStudent

2017-12-25 03:59 UTC, sarj21 requested changes
Just the one variable then it looks good

2017-12-25 04:03 UTC, sarj21 approved these changes

2017-12-25 18:39 UTC, merged

2017-12-27 00:12 UTC, jamestaylr reviewed
lgtm