Added a Volunteer Permission Level
vthacks-org/quill pull request #40
Opened 2018-02-01 03:32 UTC by sarj21

We don't want volunteers being able to edit people or see stats or send mass emails so this should allow them to only see users and check them in

2018-02-01 17:15 UTC, mecolmg commented
We should also hide the checkbox and the link button (see below)
![image](https://user-images.githubusercontent.com/8546611/35692501-854e237e-0749-11e8-8ec2-c37af9acbf80.png)

2018-02-01 17:17 UTC, sarj21 commented
Oh I should hide the checkbox and also check that it bounces volunteers. I think I want to leave the link button so volunteers can pull up a persons details if they need to. I might just want to scrub the results of some stuff they dont need to see. We can ask the others what they think

2018-02-07 04:26 UTC, sarj21 commented
This seems to work now. The checkboxes are hidden from volunteers and they can't hit any important admin only pages. Also, I stepped them down to demi-gods

2018-02-11 18:02 UTC, mecolmg requested changes
Also, the volunteers currently don't have access to the `user` page that the little link button goes to, mainly because that page allows updating user info. Volunteers can see user info by clicking on the row, so there's no reason for them to see the link.

2018-02-11 18:02 UTC, mecolmg commented on app/client/views/admin/users/users.html
> +            <th ng-if="selectedUser.admin"></th>
Should be `currentUser.admin`

This currently breaks admin view normally.

2018-02-11 20:32 UTC, sarj21 commented
Yeah my confusion, I forgot what the link button did. And I used the wrong user source. It looks like its fixed

2018-02-12 16:22 UTC, mecolmg approved these changes

2018-02-12 17:13 UTC, merged